name: Linting

on:
  - pull_request

jobs:
  lint:
    strategy:
      matrix:
        node-version:
          - 14.x
        os:
          - ubuntu-18.04
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        working-directory: ./contracts
        run: npm ci

      - name: Lint
        working-directory: ./contracts
        run: npm run lint
